configured_endpoints: 87
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/circleco%2Fheadless-client-sdk-36f367749df613ec82334040a614e68eeb227d4ff43a7322c514773166d70bd6.yml
